(() => {
  const translations = {
    zh: {
      "When Do Humans Change Their Minds?": "人类何时会改变想法？",
      "A detailed proposal for comparing interpretable reinforcement-learning models with RNN/GRU models across stable, drifting, and changing human bandit tasks.": "一份详细的研究方案：在稳定、漂移和变化的人类多臂老虎机任务中，比较可解释强化学习模型与 RNN/GRU 模型。",
      "Azulejos human RL data": "Azulejos 人类强化学习数据",
      "397,085 valid choices analysed": "已分析 397,085 个有效选择",
      "valid choices analysed": "个有效选择已分析",
      "Preliminary descriptive results": "初步描述性结果",
      "Held-out prediction plan": "留出数据预测方案",
      "Summary": "摘要", "Dataset": "数据集", "Findings": "初步发现", "Research question": "研究问题", "Models": "模型", "Method": "方法", "Interpretation": "结果解释", "Limitations": "局限",
      "1. Executive summary": "1. 执行摘要",
      "The Azulejos dataset records how people learn across a large space of reinforcement-learning bandit tasks. Our preliminary analysis suggests that participants learn reliably, but tasks involving uncertain or changing reward probabilities are especially difficult.": "Azulejos 数据集记录了人们如何在大量强化学习多臂老虎机任务中学习。初步分析表明，参与者总体上能够学习，但奖励概率不确定或发生变化的任务尤其困难。",
      "Do humans adapt differently to changes in reward probability, reward magnitude, and state structure—and can adaptive-learning-rate models explain these differences as well as flexible GRU models?": "人类对奖励概率、奖励大小和状态结构的变化是否采用不同的适应方式？动态学习率模型能否像灵活的 GRU 一样解释这些差异？",
      "The project tests where a simple, interpretable account of learning is sufficient and where a flexible recurrent model adds genuine predictive value. The goal is not merely to find the lowest loss, but to identify the simplest model that still explains and predicts human behaviour.": "本项目检验简单、可解释的学习机制在何处已经足够，以及灵活的循环模型在何处带来真正的预测价值。目标不仅是找到损失最低的模型，而是找到仍能解释并预测人类行为的最简单模型。",
      "2. Dataset and analysis sample": "2. 数据集与分析样本",
      "The public data were downloaded from the": "公开数据下载自",
      "Azulejos OSF project": "Azulejos OSF 项目",
      ". Training session 0 was excluded, and formal choice trials were identified using": "。分析排除了训练 session 0，并用",
      ". One legacy-format CSV was excluded from this initial analysis because it does not contain the current schema.": "识别正式选择试次。一个旧格式 CSV 因不符合当前数据结构而未纳入初步分析。",
      "unique participant IDs": "个不同的参与者 ID", "formal task sessions": "个正式任务 session", "valid human choices": "个人类有效选择", "unique task numbers": "个不同的任务编号",
      "What is recorded on each choice trial?": "每个选择试次记录了什么？",
      "Variable": "变量", "Meaning": "含义", "Modeling role": "建模作用",
      "The context shown on the current trial": "当前试次呈现的情境", "Defines which action may be best": "决定哪个行动可能最好",
      "The participant's selected option": "参与者选择的选项", "The choice the model must predict": "模型需要预测的选择",
      "The obtained reward": "实际获得的奖励", "Generates prediction errors and learning": "产生预测误差并驱动学习",
      "Recorded outcomes for the available options": "可选行动的记录结果", "Used to infer the best arm descriptively": "用于描述性地判断最佳选项",
      "Task features": "任务特征", "Actions, states, visibility, probability and point dynamics": "行动、状态、信息可见性、概率和分数变化", "Define regions of the task space": "定义任务空间中的不同区域",
      "3. Preliminary findings": "3. 初步发现",
      "Participants learned across trials": "参与者会随着试次学习", "Best-action accuracy was": "最佳行动准确率为", "compared with an average chance level of 35.4%. Performance in the last five state exposures was 13.2 percentage points higher than in the first five.": "，高于平均随机水平 35.4%。每个状态最后五次出现时的表现比最初五次高 13.2 个百分点。",
      "Information visibility mattered": "信息可见性会影响表现", "Scaled accuracy above chance was 19.0% when only actions were visible, compared with": "仅行动可见时，相对随机水平校正后的准确率为 19.0%；状态与行动同时可见时则为", "when states and actions were both available.": "。",
      "Probability changes were difficult": "概率变化尤其困难", "Scaled accuracy was": "校正后的准确率为", "when probability structure changed, compared with 26.4% for state-count changes and 27.2% for point-structure changes.": "（概率结构变化），而状态数量变化和分数结构变化分别为 26.4% 与 27.2%。",
      "Clear stable probabilities were easiest": "清晰且稳定的概率最容易", "Binary-and-stable probability tasks reached": "二元且稳定概率任务达到", "scaled accuracy, versus 16.7% for continuous stable and 15.4% for continuous drifting probabilities.": "的校正准确率；连续稳定概率为 16.7%，连续漂移概率为 15.4%。",
      "Figure 1. Session-level descriptive performance in the task-space sample. The vertical axis is best-action accuracy scaled relative to each task's chance level; error bars show SEM. Categories with fewer than 10 sessions are omitted.": "图 1. 任务空间样本中的 session 层面描述性表现。纵轴为相对于各任务随机水平校正后的最佳行动准确率；误差线表示均值标准误。少于 10 个 session 的类别未显示。",
      "Interpret carefully:": "请谨慎解释：", "these are descriptive associations, not causal effects. Task dimensions are correlated, so the next analysis must control for action count, state count, visibility, and reward structure simultaneously.": "这些是描述性关联，不是因果效应。任务维度彼此相关，因此后续分析必须同时控制行动数量、状态数量、信息可见性和奖励结构。",
      "4. Research question and hypotheses": "4. 研究问题与假设", "Primary research question": "主要研究问题",
      "Can interpretable reinforcement-learning models explain how humans adapt to different types of environmental change, and when do RNN/GRU models provide better held-out choice predictions?": "可解释的强化学习模型能否说明人类如何适应不同类型的环境变化？RNN/GRU 又会在何种情况下提供更好的留出选择预测？",
      "Specific version": "具体问题", "Do humans adapt differently to changes in reward probability than to changes in reward magnitude or state structure?": "与奖励大小或状态结构变化相比，人类对奖励概率变化的适应方式是否不同？",
      "H1 — Behaviour:": "H1 — 行为：", "Human choice accuracy will be lower in tasks with changing reward probabilities than in tasks with changes in reward magnitude or state structure.": "奖励概率变化任务中的人类选择准确率将低于奖励大小或状态结构变化任务。",
      "H2 — Standard RL:": "H2 — 标准强化学习：", "A standard Rescorla–Wagner model will predict choices reasonably well in stable tasks but will perform worse in volatile probability tasks.": "标准 Rescorla–Wagner 模型在稳定任务中能够合理预测选择，但在概率波动任务中表现较差。",
      "H3 — Adaptive learning:": "H3 — 动态学习：", "A model with a dynamic learning rate will improve prediction in changing environments because it can update faster when recent outcomes indicate a possible change.": "动态学习率模型会改善变化环境中的预测，因为当近期结果暗示环境发生改变时，它可以更快更新。",
      "H4 — Recurrent model:": "H4 — 循环模型：", "A GRU will provide the best overall held-out prediction, but its advantage over interpretable models will be greatest in volatile probability tasks.": "GRU 的整体留出预测最好，但它相对可解释模型的优势在概率波动任务中最大。",
      "5. Models to compare": "5. 待比较模型", "Standard Rescorla–Wagner": "标准 Rescorla–Wagner 模型", "Updates the value of the chosen action from the reward prediction error.": "根据奖励预测误差更新所选行动的价值。", "Interpretation:": "解释：", "α is learning speed; β controls how consistently the higher-valued option is chosen.": "α 表示学习速度；β 控制选择较高价值选项的一致程度。",
      "RW + forgetting": "RW + 遗忘", "Allows values of unchosen or old options to decay toward a baseline.": "允许未选择或较久未选的选项价值逐渐衰减到基线。", "Question:": "问题：", "Do people lose access to values that have not been refreshed recently?": "人们是否会逐渐遗忘近期没有更新的价值？",
      "RW + perseveration": "RW + 选择固着", "Adds a tendency to repeat the previous choice independently of learned value.": "加入与学习价值无关的重复上一选择倾向。", "Is staying caused by high expected value, or simply by choice inertia?": "继续选择是因为预期价值高，还是仅仅源于选择惯性？",
      "Adaptive learning-rate model": "动态学习率模型", "Allows α to increase when outcomes suggest that the environment has changed and decrease when the environment seems stable.": "当结果暗示环境改变时允许 α 上升，在环境看似稳定时允许 α 下降。", "Can change-sensitive updating explain behaviour in reversal, probability-switch, and drifting tasks?": "对变化敏感的更新能否解释反转、概率切换和漂移任务中的行为？",
      "Learns a flexible mapping from action–reward history to the next choice using an internal hidden state rather than a hand-written learning rule.": "利用内部隐藏状态学习从行动—奖励历史到下一次选择的灵活映射，而不是依靠手写学习规则。", "Role:": "作用：", "It provides a high-capacity predictive benchmark, but its mechanism is harder to interpret.": "它提供高容量的预测基准，但其内部机制更难解释。",
      "6. Proposed analysis": "6. 建议分析方案",
      "Build leakage-safe splits.": "建立无数据泄漏的划分。", "Split by participant or complete session, never by random individual trials. This prevents adjacent trials from the same behavioural sequence appearing in both training and test data.": "按参与者或完整 session 划分，不能随机拆分单个试次，从而避免同一行为序列中的相邻试次同时出现在训练集和测试集。",
      "Fit all models on the same training data.": "在相同训练数据上拟合所有模型。", "Give each model the information it is meant to use—previous actions and rewards, current state, and valid-action masks where appropriate.": "为每个模型提供其应使用的信息：过去的行动和奖励、当前状态，以及适用时的有效行动掩码。",
      "Predict held-out human choices.": "预测留出的人类选择。", "For every held-out trial, obtain the probability assigned to the action that the participant actually selected.": "对每个留出试次，计算模型赋予参与者实际所选行动的概率。",
      "Compute held-out negative log-likelihood.": "计算留出负对数似然。", "Lower NLL means that a model assigned higher probability to observed choices. This is the primary comparison because it rewards generalization rather than memorization.": "NLL 越低，表示模型对实际选择赋予的概率越高。它是主要比较指标，因为它衡量泛化而非记忆训练数据。",
      "Stratify by change type.": "按变化类型分层。", "Compare stable, drifting, high-volatility, probability-change, magnitude-change, and state-structure conditions.": "比较稳定、漂移、高波动、概率变化、奖励大小变化和状态结构变化条件。",
      "Interpret the performance gap.": "解释性能差距。", "Test whether adding forgetting, perseveration, or adaptive learning closes the gap between standard RW and GRU.": "检验加入遗忘、选择固着或动态学习是否能缩小标准 RW 与 GRU 的差距。",
      "Primary evaluation metrics": "主要评估指标", "Metric": "指标", "Purpose": "用途", "Better value": "更优方向",
      "Probability assigned to observed choices in unseen sessions": "模型对未见 session 中实际选择赋予的概率", "Lower": "越低越好", "Improvement over a random-choice model": "相对随机选择模型的提升", "Higher": "越高越好", "Accuracy / calibration": "准确率 / 校准度", "Whether predicted choice probabilities agree with observed frequencies": "预测选择概率是否与实际频率一致", "Higher / better aligned": "越高 / 越一致越好", "Where flexible recurrence adds predictive value": "灵活循环结构在哪些条件下增加预测价值", "Larger means GRU advantage": "越大表示 GRU 优势越明显",
      "7. How to interpret possible results": "7. 如何解释可能的结果", "Possible result": "可能结果", "Scientific interpretation": "科学解释",
      "Standard RW matches GRU in stable tasks": "标准 RW 在稳定任务中与 GRU 相当", "Simple prediction-error learning may be sufficient when contingencies are stationary.": "当环境关系保持稳定时，简单的预测误差学习可能已经足够。", "Adaptive RW closes the GRU gap in changing tasks": "动态 RW 在变化任务中缩小与 GRU 的差距", "Much of the recurrent advantage may be explained by change-sensitive learning rates.": "循环模型的大部分优势可能可由对变化敏感的学习率解释。", "Perseveration improves prediction broadly": "选择固着普遍改善预测", "Choice repetition reflects inertia as well as learned value.": "重复选择既反映选择惯性，也反映已学价值。", "GRU remains clearly better in volatile tasks": "GRU 在波动任务中仍明显更好", "Human choices may depend on longer history, nonlinear interactions, or latent beliefs not captured by the interpretable models.": "人类选择可能依赖更长的历史、非线性交互或可解释模型未捕捉的潜在信念。", "GRU wins only on training data": "GRU 只在训练数据上占优", "The network is likely overfitting rather than discovering general behavioural structure.": "网络可能只是过拟合，而非发现了可泛化的行为结构。",
      "Recommended final figure set": "建议的最终图表", "Human learning curves by task-change type.": "按任务变化类型绘制人类学习曲线。", "Held-out NLL for each model and change type.": "展示各模型与变化类型的留出 NLL。", "GRU advantage over RW:": "GRU 相对 RW 的优势：", "Parameter estimates for learning rate, perseveration, and forgetting across task conditions.": "比较各任务条件的学习率、选择固着和遗忘参数估计。", "Calibration curves comparing predicted and observed choice probabilities.": "比较预测与实际选择概率的校准曲线。",
      "8. Limitations and next steps": "8. 局限与后续步骤", "Confounding:": "混杂：", "task dimensions are not fully independent; descriptive condition means should not be interpreted causally.": "任务维度并非完全独立，不能把各条件的描述性均值解释为因果效应。", "Dynamic optimum:": "动态最优选项：", "the current descriptive “best action” averages recorded outcomes within each session and state. Drifting tasks need a trial-level expected-value or change-point analysis.": "目前描述性的“最佳行动”是对每个 session 和状态中的记录结果取平均；漂移任务需要试次层面的期望价值或变化点分析。", "Model fairness:": "模型公平性：", "models must use the same held-out split and comparable information; parameter count alone does not make train-set AIC/BIC a fair neural-model comparison.": "模型必须使用相同留出划分和可比信息；仅按参数数量计算训练集 AIC/BIC，无法公平比较神经模型。", "Participant structure:": "参与者结构：", "repeated task sessions from the same person must remain together during evaluation.": "评估时，同一参与者的重复任务 session 必须保留在同一划分中。", "Immediate next step": "下一步", "Implement a leakage-safe participant-level split and fit three first-line models—standard RW, RW with perseveration, and GRU—before adding forgetting and adaptive learning. This gives a clean baseline comparison and shows where additional complexity is justified.": "先建立无泄漏的参与者层面划分，并拟合三个首要模型——标准 RW、带选择固着的 RW 和 GRU——之后再加入遗忘与动态学习。这能提供清晰的基线比较，并显示额外复杂性在何处确有必要。", "Short spoken summary for the teacher": "向老师口头汇报的简短版本", "Our preliminary analysis suggests that participants learned across trials, but changes in reward probability were particularly difficult. We want to test whether standard and adaptive reinforcement-learning models can explain this difficulty, and whether a GRU provides additional predictive value on held-out choices. The key question is not simply which model fits best, but where flexible recurrence adds information beyond interpretable cognitive mechanisms.": "初步分析表明，参与者会随着试次学习，但奖励概率变化尤其困难。我们希望检验标准与动态强化学习模型能否解释这种困难，以及 GRU 是否能在留出选择上提供额外预测价值。关键问题不只是哪个模型拟合最好，而是灵活的循环结构在哪些地方提供了超出可解释认知机制的信息。",
      "Prepared from the currently available Azulejos OSF subset and the IICCSSS 2026 RL Masterclass repository. Preliminary results are intended for hypothesis generation.": "基于目前可获得的 Azulejos OSF 数据子集和 IICCSSS 2026 RL Masterclass 仓库制作。初步结果仅用于生成研究假设。"
    },
    ja: {
      "When Do Humans Change Their Minds?": "人はいつ考えを変えるのか？",
      "A detailed proposal for comparing interpretable reinforcement-learning models with RNN/GRU models across stable, drifting, and changing human bandit tasks.": "安定・ドリフト・変化する人間のバンディット課題において、解釈可能な強化学習モデルと RNN/GRU を比較する詳細な研究提案。",
      "Azulejos human RL data": "Azulejos 人間強化学習データ", "valid choices analysed": "件の有効な選択を分析", "Preliminary descriptive results": "予備的な記述結果", "Held-out prediction plan": "ホールドアウト予測計画",
      "397,085 valid choices analysed": "397,085 件の有効な選択を分析",
      "Summary": "概要", "Dataset": "データセット", "Findings": "予備的知見", "Research question": "研究課題", "Models": "モデル", "Method": "方法", "Interpretation": "結果の解釈", "Limitations": "限界",
      "1. Executive summary": "1. エグゼクティブ・サマリー",
      "The Azulejos dataset records how people learn across a large space of reinforcement-learning bandit tasks. Our preliminary analysis suggests that participants learn reliably, but tasks involving uncertain or changing reward probabilities are especially difficult.": "Azulejos データセットは、多様な強化学習バンディット課題における人間の学習を記録している。予備分析では参加者は着実に学習したが、報酬確率が不確実または変化する課題は特に難しかった。",
      "Do humans adapt differently to changes in reward probability, reward magnitude, and state structure—and can adaptive-learning-rate models explain these differences as well as flexible GRU models?": "人は報酬確率、報酬量、状態構造の変化に異なる方法で適応するのか。また、動的学習率モデルは柔軟な GRU と同程度にその違いを説明できるのか？",
      "The project tests where a simple, interpretable account of learning is sufficient and where a flexible recurrent model adds genuine predictive value. The goal is not merely to find the lowest loss, but to identify the simplest model that still explains and predicts human behaviour.": "本研究は、単純で解釈可能な学習説明がどこまで十分か、そして柔軟な再帰モデルがどこで真の予測価値を加えるかを検証する。目的は損失が最小のモデルを探すだけでなく、人間行動を説明・予測できる最も単純なモデルを特定することである。",
      "2. Dataset and analysis sample": "2. データセットと分析サンプル", "The public data were downloaded from the": "公開データは", "Azulejos OSF project": "Azulejos OSF プロジェクト", ". Training session 0 was excluded, and formal choice trials were identified using": "から取得した。training session 0 を除外し、正式な選択試行は", ". One legacy-format CSV was excluded from this initial analysis because it does not contain the current schema.": "で特定した。現行スキーマを含まない旧形式 CSV 1 件は予備分析から除外した。",
      "unique participant IDs": "名の参加者 ID", "formal task sessions": "件の正式な課題セッション", "valid human choices": "件の有効な人間の選択", "unique task numbers": "種類の課題番号", "What is recorded on each choice trial?": "各選択試行には何が記録されているか？", "Variable": "変数", "Meaning": "意味", "Modeling role": "モデル上の役割", "The context shown on the current trial": "現在の試行で提示された文脈", "Defines which action may be best": "どの行動が最適かを規定", "The participant's selected option": "参加者が選んだ選択肢", "The choice the model must predict": "モデルが予測すべき選択", "The obtained reward": "得られた報酬", "Generates prediction errors and learning": "予測誤差と学習を生む", "Recorded outcomes for the available options": "選択可能な行動の記録結果", "Used to infer the best arm descriptively": "最良のアームを記述的に推定", "Task features": "課題特徴", "Actions, states, visibility, probability and point dynamics": "行動、状態、情報の可視性、確率、得点の変化", "Define regions of the task space": "課題空間の領域を定義",
      "3. Preliminary findings": "3. 予備的知見", "Participants learned across trials": "参加者は試行を通じて学習した", "Best-action accuracy was": "最良行動の正答率は", "compared with an average chance level of 35.4%. Performance in the last five state exposures was 13.2 percentage points higher than in the first five.": "で、平均チャンス水準 35.4% を上回った。各状態の最後の5回では最初の5回より13.2ポイント高かった。", "Information visibility mattered": "情報の可視性が成績に影響した", "Scaled accuracy above chance was 19.0% when only actions were visible, compared with": "行動のみ可視の場合のチャンス補正正答率は19.0%、状態と行動の両方が可視の場合は", "when states and actions were both available.": "だった。", "Probability changes were difficult": "確率変化は難しかった", "Scaled accuracy was": "補正正答率は", "when probability structure changed, compared with 26.4% for state-count changes and 27.2% for point-structure changes.": "（確率構造の変化）であり、状態数変化では26.4%、得点構造変化では27.2%だった。", "Clear stable probabilities were easiest": "明確で安定した確率が最も容易だった", "Binary-and-stable probability tasks reached": "二値かつ安定した確率課題では", "scaled accuracy, versus 16.7% for continuous stable and 15.4% for continuous drifting probabilities.": "の補正正答率に達した。連続安定確率では16.7%、連続ドリフト確率では15.4%だった。",
      "Figure 1. Session-level descriptive performance in the task-space sample. The vertical axis is best-action accuracy scaled relative to each task's chance level; error bars show SEM. Categories with fewer than 10 sessions are omitted.": "図1. 課題空間サンプルにおけるセッション単位の記述的成績。縦軸は各課題のチャンス水準に対して補正した最良行動正答率で、誤差線は平均値の標準誤差を示す。10セッション未満のカテゴリは省略した。", "Interpret carefully:": "解釈上の注意：", "these are descriptive associations, not causal effects. Task dimensions are correlated, so the next analysis must control for action count, state count, visibility, and reward structure simultaneously.": "これは記述的な関連であり因果効果ではない。課題次元は相関しているため、次の分析では行動数、状態数、可視性、報酬構造を同時に統制する必要がある。",
      "4. Research question and hypotheses": "4. 研究課題と仮説", "Primary research question": "主要な研究課題", "Can interpretable reinforcement-learning models explain how humans adapt to different types of environmental change, and when do RNN/GRU models provide better held-out choice predictions?": "解釈可能な強化学習モデルは、人が異なる環境変化にどう適応するかを説明できるか。また、RNN/GRU はどの状況でホールドアウト選択をよりよく予測するか？", "Specific version": "具体的な問い", "Do humans adapt differently to changes in reward probability than to changes in reward magnitude or state structure?": "人は報酬量や状態構造の変化と比べ、報酬確率の変化に異なる方法で適応するか？",
      "H1 — Behaviour:": "H1 — 行動：", "Human choice accuracy will be lower in tasks with changing reward probabilities than in tasks with changes in reward magnitude or state structure.": "報酬確率が変化する課題では、報酬量または状態構造が変化する課題より人間の選択正答率が低い。", "H2 — Standard RL:": "H2 — 標準 RL：", "A standard Rescorla–Wagner model will predict choices reasonably well in stable tasks but will perform worse in volatile probability tasks.": "標準 Rescorla–Wagner モデルは安定課題では選択を十分に予測するが、確率が不安定な課題では悪化する。", "H3 — Adaptive learning:": "H3 — 適応的学習：", "A model with a dynamic learning rate will improve prediction in changing environments because it can update faster when recent outcomes indicate a possible change.": "動的学習率モデルは、最近の結果が変化を示すと素早く更新できるため、変化環境で予測を改善する。", "H4 — Recurrent model:": "H4 — 再帰モデル：", "A GRU will provide the best overall held-out prediction, but its advantage over interpretable models will be greatest in volatile probability tasks.": "GRU は全体として最良のホールドアウト予測を示すが、解釈可能モデルに対する優位性は確率が不安定な課題で最大となる。",
      "5. Models to compare": "5. 比較するモデル", "Standard Rescorla–Wagner": "標準 Rescorla–Wagner", "Updates the value of the chosen action from the reward prediction error.": "報酬予測誤差から選択した行動の価値を更新する。", "Interpretation:": "解釈：", "α is learning speed; β controls how consistently the higher-valued option is chosen.": "α は学習速度、β は価値の高い選択肢をどれほど一貫して選ぶかを表す。", "RW + forgetting": "RW + 忘却", "Allows values of unchosen or old options to decay toward a baseline.": "選ばれていない、または古い選択肢の価値が基準値へ減衰する。", "Question:": "問い：", "Do people lose access to values that have not been refreshed recently?": "最近更新されていない価値を人は忘れるのか？", "RW + perseveration": "RW + 固執性", "Adds a tendency to repeat the previous choice independently of learned value.": "学習された価値とは独立に直前の選択を繰り返す傾向を加える。", "Is staying caused by high expected value, or simply by choice inertia?": "同じ選択を続けるのは期待価値が高いためか、単なる選択慣性か？", "Adaptive learning-rate model": "動的学習率モデル", "Allows α to increase when outcomes suggest that the environment has changed and decrease when the environment seems stable.": "結果が環境変化を示すと α が上昇し、安定していると低下する。", "Can change-sensitive updating explain behaviour in reversal, probability-switch, and drifting tasks?": "変化に敏感な更新は、反転・確率切替・ドリフト課題の行動を説明できるか？", "Learns a flexible mapping from action–reward history to the next choice using an internal hidden state rather than a hand-written learning rule.": "手作業で定めた学習則ではなく内部隠れ状態を用い、行動・報酬履歴から次の選択への柔軟な対応を学習する。", "Role:": "役割：", "It provides a high-capacity predictive benchmark, but its mechanism is harder to interpret.": "高容量な予測ベンチマークとなるが、メカニズムの解釈は難しい。",
      "6. Proposed analysis": "6. 提案する分析", "Build leakage-safe splits.": "漏洩のないデータ分割を作る。", "Split by participant or complete session, never by random individual trials. This prevents adjacent trials from the same behavioural sequence appearing in both training and test data.": "参加者または完全なセッション単位で分割し、個々の試行をランダムに分けない。同一行動系列の隣接試行が訓練・テスト双方に入ることを防ぐ。", "Fit all models on the same training data.": "全モデルを同じ訓練データで適合する。", "Give each model the information it is meant to use—previous actions and rewards, current state, and valid-action masks where appropriate.": "過去の行動と報酬、現在の状態、必要に応じた有効行動マスクを各モデルに与える。", "Predict held-out human choices.": "ホールドアウトされた人間の選択を予測する。", "For every held-out trial, obtain the probability assigned to the action that the participant actually selected.": "各ホールドアウト試行で、参加者が実際に選んだ行動にモデルが割り当てる確率を求める。", "Compute held-out negative log-likelihood.": "ホールドアウト負の対数尤度を計算する。", "Lower NLL means that a model assigned higher probability to observed choices. This is the primary comparison because it rewards generalization rather than memorization.": "NLL が低いほど観測された選択に高い確率を割り当てている。記憶ではなく汎化を評価できるため主要指標とする。", "Stratify by change type.": "変化タイプ別に層別化する。", "Compare stable, drifting, high-volatility, probability-change, magnitude-change, and state-structure conditions.": "安定、ドリフト、高変動、確率変化、報酬量変化、状態構造変化の条件を比較する。", "Interpret the performance gap.": "性能差を解釈する。", "Test whether adding forgetting, perseveration, or adaptive learning closes the gap between standard RW and GRU.": "忘却、固執性、適応的学習の追加が標準 RW と GRU の差を縮めるか検証する。",
      "Primary evaluation metrics": "主要な評価指標", "Metric": "指標", "Purpose": "目的", "Better value": "良い方向", "Probability assigned to observed choices in unseen sessions": "未知セッションの観測選択に割り当てた確率", "Lower": "低い", "Improvement over a random-choice model": "ランダム選択モデルからの改善", "Higher": "高い", "Accuracy / calibration": "正答率 / 較正", "Whether predicted choice probabilities agree with observed frequencies": "予測確率と観測頻度が一致するか", "Higher / better aligned": "高い / 一致", "Where flexible recurrence adds predictive value": "柔軟な再帰が予測価値を加える条件", "Larger means GRU advantage": "大きいほど GRU が優位",
      "7. How to interpret possible results": "7. 結果の解釈方法", "Possible result": "考えられる結果", "Scientific interpretation": "科学的解釈", "Standard RW matches GRU in stable tasks": "安定課題で標準 RW と GRU が同等", "Simple prediction-error learning may be sufficient when contingencies are stationary.": "環境関係が一定なら単純な予測誤差学習で十分かもしれない。", "Adaptive RW closes the GRU gap in changing tasks": "変化課題で適応的 RW が GRU との差を縮める", "Much of the recurrent advantage may be explained by change-sensitive learning rates.": "再帰モデルの優位性の多くは変化に敏感な学習率で説明できる可能性がある。", "Perseveration improves prediction broadly": "固執性が広く予測を改善", "Choice repetition reflects inertia as well as learned value.": "選択の反復は学習価値だけでなく慣性も反映する。", "GRU remains clearly better in volatile tasks": "変動課題で GRU が依然として明確に優れる", "Human choices may depend on longer history, nonlinear interactions, or latent beliefs not captured by the interpretable models.": "人間の選択は、解釈可能モデルが捉えない長い履歴、非線形相互作用、潜在的信念に依存する可能性がある。", "GRU wins only on training data": "GRU が訓練データだけで優れる", "The network is likely overfitting rather than discovering general behavioural structure.": "一般的な行動構造の発見ではなく過適合の可能性が高い。", "Recommended final figure set": "推奨する最終図表", "Human learning curves by task-change type.": "課題変化タイプ別の人間の学習曲線。", "Held-out NLL for each model and change type.": "モデル・変化タイプ別のホールドアウト NLL。", "GRU advantage over RW:": "RW に対する GRU の優位性：", "Parameter estimates for learning rate, perseveration, and forgetting across task conditions.": "課題条件ごとの学習率、固執性、忘却のパラメータ推定。", "Calibration curves comparing predicted and observed choice probabilities.": "予測選択確率と観測選択確率を比較する較正曲線。",
      "8. Limitations and next steps": "8. 限界と次のステップ", "Confounding:": "交絡：", "task dimensions are not fully independent; descriptive condition means should not be interpreted causally.": "課題次元は完全に独立ではなく、条件平均を因果的に解釈すべきではない。", "Dynamic optimum:": "動的最適行動：", "the current descriptive “best action” averages recorded outcomes within each session and state. Drifting tasks need a trial-level expected-value or change-point analysis.": "現在の記述的「最良行動」は各セッション・状態内の記録結果を平均している。ドリフト課題には試行単位の期待価値または変化点分析が必要である。", "Model fairness:": "モデル比較の公平性：", "models must use the same held-out split and comparable information; parameter count alone does not make train-set AIC/BIC a fair neural-model comparison.": "モデルは同じホールドアウト分割と比較可能な情報を使う必要がある。パラメータ数だけを用いた訓練セット AIC/BIC はニューラルモデルとの公平な比較にならない。", "Participant structure:": "参加者構造：", "repeated task sessions from the same person must remain together during evaluation.": "同一人物の反復課題セッションは評価時に同じ分割にまとめる必要がある。", "Immediate next step": "直近の次のステップ", "Implement a leakage-safe participant-level split and fit three first-line models—standard RW, RW with perseveration, and GRU—before adding forgetting and adaptive learning. This gives a clean baseline comparison and shows where additional complexity is justified.": "まず漏洩のない参加者単位の分割を作り、標準 RW、固執性つき RW、GRU の3モデルを適合する。その後に忘却と適応的学習を加えることで、明確な基準比較と追加の複雑性が必要な条件を示せる。", "Short spoken summary for the teacher": "先生への短い口頭説明", "Our preliminary analysis suggests that participants learned across trials, but changes in reward probability were particularly difficult. We want to test whether standard and adaptive reinforcement-learning models can explain this difficulty, and whether a GRU provides additional predictive value on held-out choices. The key question is not simply which model fits best, but where flexible recurrence adds information beyond interpretable cognitive mechanisms.": "予備分析では参加者は試行を通じて学習しましたが、報酬確率の変化は特に難しいことが分かりました。標準および適応的強化学習モデルがこの難しさを説明できるか、また GRU がホールドアウト選択に追加の予測価値を与えるかを検証します。重要なのは単に最も適合するモデルではなく、柔軟な再帰が解釈可能な認知メカニズムを超えてどこで情報を加えるかです。", "Prepared from the currently available Azulejos OSF subset and the IICCSSS 2026 RL Masterclass repository. Preliminary results are intended for hypothesis generation.": "現在利用可能な Azulejos OSF サブセットと IICCSSS 2026 RL Masterclass リポジトリに基づいて作成。予備結果は仮説生成を目的とする。"
    }
  };

  const original = new WeakMap();
  const nodes = [];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      if (!node.nodeValue.trim() || node.parentElement.closest("script, style, code, .formula, .language-bar")) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    }
  });
  while (walker.nextNode()) {
    const node = walker.currentNode;
    original.set(node, node.nodeValue);
    nodes.push(node);
  }

  function setLanguage(language) {
    const dictionary = translations[language] || {};
    for (const node of nodes) {
      const source = original.get(node);
      const trimmed = source.trim();
      const translated = dictionary[trimmed];
      node.nodeValue = translated ? source.replace(trimmed, translated) : source;
    }
    document.documentElement.lang = language === "zh" ? "zh-CN" : language;
    document.querySelector("nav").setAttribute("aria-label", language === "zh" ? "报告章节" : language === "ja" ? "レポートのセクション" : "Report sections");
    document.querySelector(".language-bar").setAttribute("aria-label", language === "zh" ? "语言选择" : language === "ja" ? "言語選択" : "Language selector");
    document.title = language === "zh" ? "Azulejos 人类强化学习——建模研究方案" : language === "ja" ? "Azulejos 人間強化学習 — モデリング研究提案" : "Azulejos Human RL — Modeling Research Proposal";
    document.querySelectorAll("[data-language]").forEach(button => button.setAttribute("aria-pressed", String(button.dataset.language === language)));
    localStorage.setItem("report-language", language);
  }

  document.querySelectorAll("[data-language]").forEach(button => button.addEventListener("click", () => setLanguage(button.dataset.language)));
  setLanguage(localStorage.getItem("report-language") || (navigator.language.startsWith("zh") ? "zh" : navigator.language.startsWith("ja") ? "ja" : "en"));
})();
